# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YTWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YTDownloader(object):
    def setupUi(self, YTDownloader):
        YTDownloader.setObjectName("YTDownloader")
        YTDownloader.resize(640, 480)
        YTDownloader.setMinimumSize(QtCore.QSize(640, 480))
        YTDownloader.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        YTDownloader.setWindowIcon(icon)
        YTDownloader.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.centralwidget = QtWidgets.QWidget(YTDownloader)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget.setMaximumSize(QtCore.QSize(640, 480))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 441))
        self.verticalLayoutWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: #fefefe;\n"
"    border-width: 1px;\n"
"    border-color: #ffcc33;\n"
"    border-style: solid;\n"
"    border-radius: 8px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setStyleSheet("background-color: rgb(255, 204, 51);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setStyleSheet("background-color: rgb(177, 177, 177);\n"
"color: #000;\n"
"border-width: 1px;\n"
"border-color: #ffcc33;\n"
"border-style: solid;\n"
"height: 30px;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: #fff;\n"
"    border-width: 1px;\n"
"    border-color: #ffcc33;\n"
"    border-style: solid;\n"
"    border-radius: 20px;\n"
"    height: 40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #646464;\n"
"    color: #fff;\n"
"    border-width: 1px;    \n"
"    border-color: #ffcc33;\n"
"    border-style: solid;\n"
"    border-radius: 20px;\n"
"    height: 40;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#fff;\n"
"    color: #000;\n"
"    border-width: 1px;    \n"
"    border-color: #ffcc33;\n"
"    border-style: solid;\n"
"    border-radius: 20px;\n"
"    height: 40;\n"
"}")
        self.pushButton_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMouseTracking(False)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: #fff;\n"
"    border-width: 1px;\n"
"    border-color: #ffcc33;\n"
"    border-style: solid;\n"
"    border-radius: 20px;\n"
"    height: 40;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #646464;\n"
"    color: rgb(100, 100, 100);\n"
"    color: #fff;\n"
"    border-width: 1px;    \n"
"    border-color: #ffcc33;\n"
"    border-style: solid;\n"
"    border-radius: 20px;\n"
"    height: 40;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#fff;\n"
"    color: #000;\n"
"    border-width: 1px;    \n"
"    border-color: #ffcc33;\n"
"    border-style: solid;\n"
"    border-radius: 20px;\n"
"    height: 40;\n"
"}")
        self.pushButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        YTDownloader.setCentralWidget(self.centralwidget)

        self.retranslateUi(YTDownloader)
        QtCore.QMetaObject.connectSlotsByName(YTDownloader)

    def retranslateUi(self, YTDownloader):
        _translate = QtCore.QCoreApplication.translate
        YTDownloader.setWindowTitle(_translate("YTDownloader", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("YTDownloader", "Process..."))
        self.lineEdit.setText(_translate("YTDownloader", "Paste youtube URL here..."))
        self.pushButton_2.setText(_translate("YTDownloader", "Download a video"))
        self.pushButton.setText(_translate("YTDownloader", "Choose folder where to save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YTDownloader = QtWidgets.QMainWindow()
    ui = Ui_YTDownloader()
    ui.setupUi(YTDownloader)
    YTDownloader.show()
    sys.exit(app.exec_())
